#!/bin/bash
yum update -y
yum install httpd -y
echo "<html><body><center><h1> Hello World 1 </h1></center></html>" > /var/www/html/index.html
echo "this is test123"
systemctl start httpd
systemctl enable httpd
